# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

Pet.create!([
  {
    name: "Moose Doodle",
    race: "Dog",
    breed: "Golden Doodle",
    birthday: Date.new(2020, 6, 3),
    favoriteFood: "Raw Meat",
    picUrl: "https://www.dogbreedslist.info/uploads/dog-pictures/dachshund-2.jpg",
    price: 0.99999999e8,
    picUrlSq: "http://www.dogbreedplus.com/dog_breeds/images/cute-rottweiler-puppy.jpg",
    description: "The best doggo. A wonderful companion for people of all ages. Friendly, playful, and always ready for a walk.A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.",
    created_at: "2023-05-28 02:41:02.506406",
    updated_at: "2023-05-28 12:38:16.715979",
    fetch: true
  },
  {
    name: "T-Rex rex",
    race: "Dog",
    breed: "Rottweiler",
    birthday: Date.new(2017, 11, 11),
    favoriteFood: "Chicken",
    picUrl: "https://www.dogbreedslist.info/uploads/dog-pictures/french-bulldog-2.jpg",
    price: 0.999e1,
    picUrlSq: "http://www.dogbreedplus.com/dog_breeds/images/cute-rottweiler-puppy.jpg",
    description: "A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.",
    created_at: "2023-05-28 02:43:55.427027",
    updated_at: "2023-05-28 13:19:00.293640",
    fetch: false
  },
  {
    name: "Dido",
    race: "Dog",
    breed: "Latipoo",
    birthday: Date.new(2008, 11, 11),
    favoriteFood: "Pork heart",
    picUrl: "http://www.gpamass.com/s/img/emotionheader713297504.jpg",
    price: 0.999e1,
    picUrlSq: "https://www.collinsdictionary.com/images/thumb/greyhound_21701074_250.jpg",
    description: "A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.",
    created_at: "2023-05-28 02:46:40.734431",
    updated_at: "2023-05-28 02:46:40.734431",
    fetch: true
  },
  {
    name: "Fido",
    race: "Dog",
    breed: "Greyhound",
    birthday: Date.new(2008, 11, 11),
    favoriteFood: "Liver",
    picUrl: "http://www.gpamass.com/s/img/emotionheader713297504.jpg",
    price: 0.999e1,
    picUrlSq: "https://www.collinsdictionary.com/images/thumb/greyhound_21701074_250.jpg",
    description: "A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.",
    created_at: "2023-05-28 02:46:40.734431",
    updated_at: "2023-05-28 02:46:40.734431",
    fetch: true
  },
  {
    name: "Santa's Little Helper",
    race: "Elf",
    breed: "Mixed",
    birthday: Date.new(2008, 11, 11),
    favoriteFood: "Pork",
    picUrl: "https://www.dogbreedslist.info/uploads/dog-pictures/dachshund-2.jpg",
    price: 0.999e1,
    picUrlSq: "http://via.placeholder.com/250x250",
    description: "A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.",
    created_at: "2023-05-28 11:34:05.458387",
    updated_at: "2023-05-28 11:34:05.458387",
    fetch: false
  },
  {
    name: "Alf",
    race: "Alien",
    breed: "Alien",
    birthday: Date.new(2008, 11, 11),
    favoriteFood: "Cats",
    picUrl: "https://www.dogbreedslist.info/uploads/dog-pictures/pembroke-welsh-corgi-2.jpg",
    price: 0.5999e2,
    picUrlSq: "http://via.placeholder.com/250x250",
    description: "A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.",
    created_at: "2023-05-28 11:34:15.981001",
    updated_at: "2023-05-28 11:34:15.981001",
    fetch: true
  },
  {
    name: "Bubba",
    race: "Dog",
    breed: "Mastiff",
    birthday: Date.new(2008, 11, 11),
    favoriteFood: "Dragon",
    picUrl: "https://www.dogbreedslist.info/uploads/dog-pictures/yorkshire-terrier-2-2.jpg",
    price: 0.999e1,
    picUrlSq: "http://via.placeholder.com/250x250",
    description: "A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.",
    created_at: "2023-05-28 11:34:24.256693",
    updated_at: "2023-05-28 13:18:16.296343",
    fetch: false
  },
  {
    name: "Moose Doodle",
    race: "Dog",
    breed: "Golden Doodle",
    birthday: Date.new(2020, 6, 3),
    favoriteFood: "Raw Meat",
    picUrl: "https://www.dogbreedslist.info/uploads/dog-pictures/dachshund-2.jpg",
    price: 0.99999999e8,
    picUrlSq: "http://www.dogbreedplus.com/dog_breeds/images/cute-rottweiler-puppy.jpg",
    description: "A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.",
    created_at: "2023-05-28 02:41:02.506406",
    updated_at: "2023-05-28 12:38:16.715979",
    fetch: true
  },
  {
    name: "T-Rex rex",
    race: "Dog",
    breed: "Rottweiler",
    birthday: Date.new(2017, 11, 11),
    favoriteFood: "Chicken",
    picUrl: "https://www.dogbreedslist.info/uploads/dog-pictures/french-bulldog-2.jpg",
    price: 0.999e1,
    picUrlSq: "http://www.dogbreedplus.com/dog_breeds/images/cute-rottweiler-puppy.jpg",
    description: "A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.",
    created_at: "2023-05-28 02:43:55.427027",
    updated_at: "2023-05-28 13:19:00.293640",
    fetch: true
  },
  {
    name: "Dido",
    race: "Dog",
    breed: "Latipoo",
    birthday: Date.new(2008, 11, 11),
    favoriteFood: "Pork heart",
    picUrl: "http://www.gpamass.com/s/img/emotionheader713297504.jpg",
    price: 0.999e1,
    picUrlSq: "https://www.collinsdictionary.com/images/thumb/greyhound_21701074_250.jpg",
    description: "A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.",
    created_at: "2023-05-28 02:46:40.734431",
    updated_at: "2023-05-28 02:46:40.734431",
    fetch: false
  },
  {
    name: "Fido",
    race: "Dog",
    breed: "Greyhound",
    birthday: Date.new(2008, 11, 11),
    favoriteFood: "Liver",
    picUrl: "http://www.gpamass.com/s/img/emotionheader713297504.jpg",
    price: 0.999e1,
    picUrlSq: "https://www.collinsdictionary.com/images/thumb/greyhound_21701074_250.jpg",
    description: "A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.",
    created_at: "2023-05-28 02:46:40.734431",
    updated_at: "2023-05-28 02:46:40.734431",
    fetch: false
  },
  {
    name: "Santa's Little Helper",
    race: "Elf",
    breed: "Mixed",
    birthday: Date.new(2008, 11, 11),
    favoriteFood: "Pork",
    picUrl: "https://www.dogbreedslist.info/uploads/dog-pictures/dachshund-2.jpg",
    price: 0.999e1,
    picUrlSq: "http://via.placeholder.com/250x250",
    description: "A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.",
    created_at: "2023-05-28 11:34:05.458387",
    updated_at: "2023-05-28 11:34:05.458387",
    fetch: false
  },
  {
    name: "Alf",
    race: "Alien",
    breed: "Alien",
    birthday: Date.new(2008, 11, 11),
    favoriteFood: "Cats",
    picUrl: "https://www.dogbreedslist.info/uploads/dog-pictures/pembroke-welsh-corgi-2.jpg",
    price: 0.5999e2,
    picUrlSq: "http://via.placeholder.com/250x250",
    description: "A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.",
    created_at: "2023-05-28 11:34:15.981001",
    updated_at: "2023-05-28 11:34:15.981001",
    fetch: false
  },
  {
    name: "Bubba",
    race: "Dog",
    breed: "Mastiff",
    birthday: Date.new(2008, 11, 11),
    favoriteFood: "Dragon",
    picUrl: "https://www.dogbreedslist.info/uploads/dog-pictures/yorkshire-terrier-2-2.jpg",
    price: 0.999e1,
    picUrlSq: "http://via.placeholder.com/250x250",
    description: "A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.",
    created_at: "2023-05-28 11:34:24.256693",
    updated_at: "2023-05-28 13:18:16.296343",
    fetch: false
  },
  {
    name: "Moose Doodle",
    race: "Dog",
    breed: "Golden Doodle",
    birthday: Date.new(2020, 6, 3),
    favoriteFood: "Raw Meat",
    picUrl: "https://www.dogbreedslist.info/uploads/dog-pictures/dachshund-2.jpg",
    price: 0.99999999e8,
    picUrlSq: "http://www.dogbreedplus.com/dog_breeds/images/cute-rottweiler-puppy.jpg",
    description: "A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.",
    created_at: "2023-05-28 02:41:02.506406",
    updated_at: "2023-05-28 12:38:16.715979",
    fetch: false
  },
  {
    name: "T-Rex rex",
    race: "Dog",
    breed: "Rottweiler",
    birthday: Date.new(2017, 11, 11),
    favoriteFood: "Chicken",
    picUrl: "https://www.dogbreedslist.info/uploads/dog-pictures/french-bulldog-2.jpg",
    price: 0.999e1,
    picUrlSq: "http://www.dogbreedplus.com/dog_breeds/images/cute-rottweiler-puppy.jpg",
    description: "A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.",
    created_at: "2023-05-28 02:43:55.427027",
    updated_at: "2023-05-28 13:19:00.293640",
    fetch: false
  },
  {
    name: "Dido",
    race: "Dog",
    breed: "Latipoo",
    birthday: Date.new(2008, 11, 11),
    favoriteFood: "Pork heart",
    picUrl: "http://www.gpamass.com/s/img/emotionheader713297504.jpg",
    price: 0.999e1,
    picUrlSq: "https://www.collinsdictionary.com/images/thumb/greyhound_21701074_250.jpg",
    description: "A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.",
    created_at: "2023-05-28 02:46:40.734431",
    updated_at: "2023-05-28 02:46:40.734431",
    fetch: false
  },
  {
    name: "Fido",
    race: "Dog",
    breed: "Greyhound",
    birthday: Date.new(2008, 11, 11),
    favoriteFood: "Liver",
    picUrl: "http://www.gpamass.com/s/img/emotionheader713297504.jpg",
    price: 0.999e1,
    picUrlSq: "https://www.collinsdictionary.com/images/thumb/greyhound_21701074_250.jpg",
    description: "A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.",
    created_at: "2023-05-28 02:46:40.734431",
    updated_at: "2023-05-28 02:46:40.734431",
    fetch: false
  },
  {
    name: "Santa's Little Helper",
    race: "Elf",
    breed: "Mixed",
    birthday: Date.new(2008, 11, 11),
    favoriteFood: "Pork",
    picUrl: "https://www.dogbreedslist.info/uploads/dog-pictures/dachshund-2.jpg",
    price: 0.999e1,
    picUrlSq: "http://via.placeholder.com/250x250",
    description: "A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.",
    created_at: "2023-05-28 11:34:05.458387",
    updated_at: "2023-05-28 11:34:05.458387",
    fetch: false
  },
  {
    name: "Alf",
    race: "Alien",
    breed: "Alien",
    birthday: Date.new(2008, 11, 11),
    favoriteFood: "Cats",
    picUrl: "https://www.dogbreedslist.info/uploads/dog-pictures/pembroke-welsh-corgi-2.jpg",
    price: 0.5999e2,
    picUrlSq: "http://via.placeholder.com/250x250",
    description: "A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.",
    created_at: "2023-05-28 11:34:15.981001",
    updated_at: "2023-05-28 11:34:15.981001",
    fetch: true
  },
  {
    name: "Bubba",
    race: "Dog",
    breed: "Mastiff",
    birthday: Date.new(2008, 11, 11),
    favoriteFood: "Dragon",
    picUrl: "https://www.dogbreedslist.info/uploads/dog-pictures/yorkshire-terrier-2-2.jpg",
    price: 0.999e1,
    picUrlSq: "http://via.placeholder.com/250x250",
    description: "A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.A friendly dog. Great with children and other pets. Loves to play fetch and go for long walks in the park.",
    created_at: "2023-05-28 11:34:24.256693",
    updated_at: "2023-05-28 13:18:16.296343",
    fetch: false
  }
])
